### PR TITLE
Save config and certs under ~/.spacekit

### LINKED ISSUE #61: Don't store certs in directory spacekit is ran from
We should be storing certs in the user's home directory instead probably.

### PR DESCRIPTION
**Pull request by dracos**
This should fix #61 and also store the config under there too rather than a normal file in your homedir.

### CODE REVIEW

**Comment by jedireza** [comment]
Thanks for creating a PR! We may be slow to merge because we're updating the service and will be updating the client soon. ❤️

**Comment by Sija** [comment]
Hi! Is there anything that prevents this PR from being merged? It seems to me that it could be merged regardless of the service updates, no?

**Comment by jedireza** [comment]
Apologies for the lack of attention here.

Let's not move `~/spacekit.json` to `~/.spacekit/config.json`. I would like to see us store the certs we make in `~/spacekit-certs/` though.

Once those changes are made I'm happy to merge.

**Comment by dracos** [comment]
Could you possibly explain your suggestion? I don't see why spacekit should be able to clutter up someone's home directory with two things (config and internal certificates) that are perfectly suited for a dot-directory. It's what git, npm, bash, pypi, gem, vim, etc etc do. I don't want application files visible in my home directory.

**Comment by Sija** [comment]
@jedireza I concur with @dracos, that's exactly the _raison d'etre_ of dot-directories in user home. All good behaving programs are doing it, so what would be the reason for spacekit to break ranks in here?

**Comment by jedireza** [comment]
Valid points, thanks for sharing that. I agree.

**Comment by Sija** [comment]
@jedireza would it be possible to cut a new npm release?

**Comment by jedireza** [comment]
v4 has been published

**Comment by Sija** [comment]
@jedireza gr8, thanks!

**Pull request merged**
